---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE, fig.align = 'centre')
```


```{r}
library(tidyverse)
library(data.table)
#library(ggridges)
library(viridis)
library(slingshot)
library(mclust)
library(ggpubr)
#library(RColorBrewer)


#########################################8 kmeans clusters current best fit####################################################
```

```{r}

df <- fread("../data/08_cleaned_umap.csv")

```

#slingshot
```{r}

timecourse <- df %>%
  filter(Metadata_library=="timecourse")

timecourse$Metadata_plate <- as.factor(timecourse$Metadata_plate)

timecourse <- timecourse %>%
  mutate_at("Metadata_plate", as.factor)
  
timecourse <- timecourse[order(timecourse$Metadata_plate),]

timecourse_sub <- timecourse %>%
  group_by(Metadata_plate)%>%
  slice_sample(n=2000) %>%
  ungroup()

rm(df)


#get drugs

drugs_df <- df %>%
  filter(Metadata_library != "timecourse") %>%
  select(X1, X2, Metadata_compound, Metadata_concentration)

drugs_rd <- df %>%
  filter(Metadata_library != "timecourse") %>%
  select(X1, X2)

```


```{r}

#for kmeans clusters

#plot clusters on umap for kmeans 1:12 clusters
for (i in 1:12){
  cl <- kmeans(rd, centers = i)$cluster
  timecourse_sub$cl <- as.factor(cl)
  p <- ggplot(timecourse_sub, aes(X1, X2))+ 
  geom_point(aes(colour = cl), alpha = 0.5)+
  #scale_colour_viridis_d(option="C")+
  labs(colour="cluster")
  print(p)

}

#plot clusters on umap for kmeans 1:12 clusters
for (i in 5:12){
  cl <- Mclust(rd, G = i)$classification
  timecourse_sub$cl <- as.factor(cl)
  p <- ggplot(timecourse_sub, aes(X1, X2))+ 
  geom_point(aes(colour = cl), alpha = 0.5)+
  #scale_colour_viridis_d(option="C")+
  labs(colour="cluster")
  print(p)

}
```

```{r}
#create cluster labels
cl <- Mclust(rd, G = 5)$classification

#add cluster labels to dataframe
timecourse_sub$cl <- as.factor(cl)

ggplot(timecourse_sub, aes(X1, X2))+ 
  geom_point(aes(colour = cl), alpha = 0.5)+
  #scale_colour_viridis_d(option="C")+
  labs(colour="cluster")

fwrite(timecourse_sub, "../data/10_slingshot_clusters.csv")

```


```{r}
sce <- slingshot(as.matrix(rd), clusterLabels = cl, start.clus = "5", end.clus = c("2", "3"))


plot(rd, col = viridis(5)[cl], asp = 1, pch = 16)+
lines(SlingshotDataSet(sce), lwd = 3, col = 'black')


plot(rd, col = viridis(5)[cl], asp = 1, pch = 16)+
lines(SlingshotDataSet(sce), type = "lineages", lwd = 3, col = 'black', show.constraints = TRUE)



pseudo1 <- as.data.frame(slingPseudotime(sce))

#get vector of pseudotime values, one per data point/cell 
#(average of pseudotime across all lineages for cells belonging to multiple lineages)
pseudo_avg <- pseudo1 %>%
  rowMeans(na.rm=TRUE) 

#create vector of colours baesd on pseudotime
colors <- viridis(100)
plotcol <- colors[cut(pseudo_avg, breaks=100)]

png("../outputs/plots/05/slingshot_curves.png", type = "cairo")



plot(rd, col = plotcol, asp = 1, pch = 16)+
  lines(SlingshotDataSet(sce), lwd = 3, col = 'black')

```
```{r}

pto <- SlingshotDataSet(sce) 

newPTO <- slingshot::predict(pto, drugs_rd)

newplotcol <- colors[cut(slingPseudotime(newPTO), breaks=100)]

plot(rd, col = 'grey', bg = 'grey', pch=21, asp = 1)+
points(slingReducedDim(newPTO), col = newplotcol, pch = 16)+
lines(SlingshotDataSet(sce), lwd=2, col = 'black')

```



```{r}

drug_pto <- cbind(drugs_df,slingPseudotime(newPTO))

ecf506 <- drug_pto %>%
  filter(Metadata_compound %in% c("Progenitor", "DMSO" ,"ECF506") & Metadata_concentration %in% c("DMSO", 10, "Progenitor"))



my_comparisons <- list( c("DMSO", "ECF506"), c("ECF506", "Progenitor"), c("DMSO", "Progenitor") )

ggplot(ecf506, aes(Metadata_compound, Lineage1)) +
  geom_boxplot()+
  geom_jitter()+
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 30)

ggplot(ecf506, aes(Metadata_compound, Lineage2)) +
  geom_boxplot()+
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 25)
```










